// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package support_domains

import (
	"kgplatform-backend/api/support_domains"
)

type ControllerV1 struct{}

func NewV1() support_domains.ISupportDomainsV1 {
	return &ControllerV1{}
}
