// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"kgplatform-backend/internal/dao/internal"
)

// billingOveragesDao is the data access object for the table billing_overages.
// You can define custom methods on it to extend its functionality as needed.
type billingOveragesDao struct {
	*internal.BillingOveragesDao
}

var (
	// BillingOverages is a globally accessible object for table billing_overages operations.
	BillingOverages = billingOveragesDao{internal.NewBillingOveragesDao()}
)

// Add your custom methods and functionality below.
