// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"kgplatform-backend/internal/dao/internal"
)

// billingPaymentsDao is the data access object for the table billing_payments.
// You can define custom methods on it to extend its functionality as needed.
type billingPaymentsDao struct {
	*internal.BillingPaymentsDao
}

var (
	// BillingPayments is a globally accessible object for table billing_payments operations.
	BillingPayments = billingPaymentsDao{internal.NewBillingPaymentsDao()}
)

// Add your custom methods and functionality below.
