// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"kgplatform-backend/internal/dao/internal"
)

// billingInvoicesDao is the data access object for the table billing_invoices.
// You can define custom methods on it to extend its functionality as needed.
type billingInvoicesDao struct {
	*internal.BillingInvoicesDao
}

var (
	// BillingInvoices is a globally accessible object for table billing_invoices operations.
	BillingInvoices = billingInvoicesDao{internal.NewBillingInvoicesDao()}
)

// Add your custom methods and functionality below.
