// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"kgplatform-backend/internal/dao/internal"
)

// billingRecordsDao is the data access object for the table billing_records.
// You can define custom methods on it to extend its functionality as needed.
type billingRecordsDao struct {
	*internal.BillingRecordsDao
}

var (
	// BillingRecords is a globally accessible object for table billing_records operations.
	BillingRecords = billingRecordsDao{internal.NewBillingRecordsDao()}
)

// Add your custom methods and functionality below.
