// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"kgplatform-backend/internal/dao/internal"
)

// commentLikesDao is the data access object for the table comment_likes.
// You can define custom methods on it to extend its functionality as needed.
type commentLikesDao struct {
	*internal.CommentLikesDao
}

var (
	// CommentLikes is a globally accessible object for table comment_likes operations.
	CommentLikes = commentLikesDao{internal.NewCommentLikesDao()}
)

// Add your custom methods and functionality below.
