// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"kgplatform-backend/internal/dao/internal"
)

// domainsDao is the data access object for the table support_domains.
// You can define custom methods on it to extend its functionality as needed.
type domainsDao struct {
	*internal.DomainsDao
}

var (
	// Domains is a globally accessible object for table support_domains operations.
	Domains = domainsDao{internal.NewDomainsDao()}
)

// Add your custom methods and functionality below.
