// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"kgplatform-backend/internal/dao/internal"
)

// graphsDao is the data access object for the table graphs.
// You can define custom methods on it to extend its functionality as needed.
type graphsDao struct {
	*internal.GraphsDao
}

var (
	// Graphs is a globally accessible object for table graphs operations.
	Graphs = graphsDao{internal.NewGraphsDao()}
)

// Add your custom methods and functionality below.
