// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"kgplatform-backend/internal/dao/internal"
)

// materialsDao is the data access object for the table materials.
// You can define custom methods on it to extend its functionality as needed.
type materialsDao struct {
	*internal.MaterialsDao
}

var (
	// Materials is a globally accessible object for table materials operations.
	Materials = materialsDao{internal.NewMaterialsDao()}
)

// Add your custom methods and functionality below.
