// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"kgplatform-backend/internal/dao/internal"
)

// modelsDao is the data access object for the table models.
// You can define custom methods on it to extend its functionality as needed.
type modelsDao struct {
	*internal.ModelsDao
}

var (
	// Models is a globally accessible object for table models operations.
	Models = modelsDao{internal.NewModelsDao()}
)

// Add your custom methods and functionality below.
