// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"kgplatform-backend/internal/dao/internal"
)

// pipelinesLikesDao is the data access object for the table pipelines_likes.
// You can define custom methods on it to extend its functionality as needed.
type pipelinesLikesDao struct {
	*internal.PipelinesLikesDao
}

var (
	// PipelinesLikes is a globally accessible object for table pipelines_likes operations.
	PipelinesLikes = pipelinesLikesDao{internal.NewPipelinesLikesDao()}
)

// Add your custom methods and functionality below.
