// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"kgplatform-backend/internal/dao/internal"
)

// pipelinesFavoritesDao is the data access object for the table pipelines_favorites.
// You can define custom methods on it to extend its functionality as needed.
type pipelinesFavoritesDao struct {
	*internal.PipelinesFavoritesDao
}

var (
	// PipelinesFavorites is a globally accessible object for table pipelines_favorites operations.
	PipelinesFavorites = pipelinesFavoritesDao{internal.NewPipelinesFavoritesDao()}
)

// Add your custom methods and functionality below.
