// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"kgplatform-backend/internal/dao/internal"
)

// pipelinesDao is the data access object for the table pipelines.
// You can define custom methods on it to extend its functionality as needed.
type pipelinesDao struct {
	*internal.PipelinesDao
}

var (
	// Pipelines is a globally accessible object for table pipelines operations.
	Pipelines = pipelinesDao{internal.NewPipelinesDao()}
)

// Add your custom methods and functionality below.
