// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"kgplatform-backend/internal/dao/internal"
)

// professionalDictionaryDao is the data access object for the table professional_dictionary.
// You can define custom methods on it to extend its functionality as needed.
type professionalDictionaryDao struct {
	*internal.ProfessionalDictionaryDao
}

var (
	// ProfessionalDictionary is a globally accessible object for table professional_dictionary operations.
	ProfessionalDictionary = professionalDictionaryDao{internal.NewProfessionalDictionaryDao()}
)

// Add your custom methods and functionality below.
