// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"kgplatform-backend/internal/dao/internal"
)

// projectsLikesDao is the data access object for the table projects_likes.
// You can define custom methods on it to extend its functionality as needed.
type projectsLikesDao struct {
	*internal.ProjectsLikesDao
}

var (
	// ProjectsLikes is a globally accessible object for table projects_likes operations.
	ProjectsLikes = projectsLikesDao{internal.NewProjectsLikesDao()}
)

// Add your custom methods and functionality below.
