// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"kgplatform-backend/internal/dao/internal"
)

// supportDomainsDao is the data access object for the table support_domains.
// You can define custom methods on it to extend its functionality as needed.
type supportDomainsDao struct {
	*internal.SupportDomainsDao
}

var (
	// SupportDomains is a globally accessible object for table support_domains operations.
	SupportDomains = supportDomainsDao{internal.NewSupportDomainsDao()}
)

// Add your custom methods and functionality below.
