// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"kgplatform-backend/internal/dao/internal"
)

// teamMembersDao is the data access object for the table team_members.
// You can define custom methods on it to extend its functionality as needed.
type teamMembersDao struct {
	*internal.TeamMembersDao
}

var (
	// TeamMembers is a globally accessible object for table team_members operations.
	TeamMembers = teamMembersDao{internal.NewTeamMembersDao()}
)

// Add your custom methods and functionality below.
