// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"kgplatform-backend/internal/dao/internal"
)

// teamsDao is the data access object for the table teams.
// You can define custom methods on it to extend its functionality as needed.
type teamsDao struct {
	*internal.TeamsDao
}

var (
	// Teams is a globally accessible object for table teams operations.
	Teams = teamsDao{internal.NewTeamsDao()}
)

// Add your custom methods and functionality below.
