// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"kgplatform-backend/internal/dao/internal"
)

// trafficLogsDao is the data access object for the table traffic_logs.
// You can define custom methods on it to extend its functionality as needed.
type trafficLogsDao struct {
	*internal.TrafficLogsDao
}

var (
	// TrafficLogs is a globally accessible object for table traffic_logs operations.
	TrafficLogs = trafficLogsDao{internal.NewTrafficLogsDao()}
)

// Add your custom methods and functionality below.
