// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"kgplatform-backend/internal/dao/internal"
)

// userProjectPurchasesDao is the data access object for the table user_project_purchases.
// You can define custom methods on it to extend its functionality as needed.
type userProjectPurchasesDao struct {
	*internal.UserProjectPurchasesDao
}

var (
	// UserProjectPurchases is a globally accessible object for table user_project_purchases operations.
	UserProjectPurchases = userProjectPurchasesDao{internal.NewUserProjectPurchasesDao()}
)

// Add your custom methods and functionality below.
