// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"kgplatform-backend/internal/dao/internal"
)

// userSubscriptionsDao is the data access object for the table user_subscriptions.
// You can define custom methods on it to extend its functionality as needed.
type userSubscriptionsDao struct {
	*internal.UserSubscriptionsDao
}

var (
	// UserSubscriptions is a globally accessible object for table user_subscriptions operations.
	UserSubscriptions = userSubscriptionsDao{internal.NewUserSubscriptionsDao()}
)

// Add your custom methods and functionality below.
