// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"kgplatform-backend/internal/dao/internal"
)

// viewsDao is the data access object for the table views.
// You can define custom methods on it to extend its functionality as needed.
type viewsDao struct {
	*internal.ViewsDao
}

var (
	// Views is a globally accessible object for table views operations.
	Views = viewsDao{internal.NewViewsDao()}
)

// Add your custom methods and functionality below.
