// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package graphs

import (
	"kgplatform-backend/api/graphs"
)

type ControllerV1 struct{}

func NewV1() graphs.IGraphsV1 {
	return &ControllerV1{}
}
