// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package pipelines

import (
	"kgplatform-backend/api/pipelines"
)

type ControllerV1 struct{}

func NewV1() pipelines.IPipelinesV1 {
	return &ControllerV1{}
}
