// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package projects

import (
	_ "kgplatform-backend/api/projects"
)
