// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package professional_dictionary

import (
	"kgplatform-backend/api/professional_dictionary"
)

type ControllerV1 struct{}

func NewV1() professional_dictionary.IProfessionalDictionaryV1 {
	return &ControllerV1{}
}
