// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package tasks

import (
	"kgplatform-backend/api/tasks"
)

type ControllerV1 struct{}

func NewV1() tasks.ITasksV1 {
	return &ControllerV1{}
}
